version: "3"
services:
  web:
    container_name: apache
    restart: always
    image: php:5.6.14-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:mixtape.giovannitufo.me"
      - "traefik.frontend.protocol=https"
      - "traefik.port=80"
networks:
  traefik:
    external: true